# Generated by Django 5.0 on 2025-08-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='categories',
            field=models.ManyToManyField(related_name='user_pref_categories', to='news.category'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_categories',
            field=models.ManyToManyField(related_name='user_pref_preferred', to='news.category'),
        ),
    ]
