# Generated by Django 5.0 on 2025-08-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_userpreference_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
